### ISSUE TITLE
Copious INFO logging

### ISSUE THREAD

**Issue by tripleee** [metachris/pdfx#41]
Running this from a Python script with `logging.basicConfig(level=logging.INFO)` creates incredible amounts of detailed logging which would probably best be confined to `level=logging.DEBUG` and/or ideally possible to turn off if you don't cate about the library's internals.

**Comment by czechnology** [comment]
While I agree with this issue, I think it's caused by the underlying [pdfminer2][1] package, which seems to make strong use of `logging.info` calls, using the root handler, thus not allowing to disable it easily.

On the same topic, that library seems to be unmaintained by Chris (last commit Dec 2015), maybe it would make sense to switch to the [pdfminer.six][2] library (from which pdfminer2 is originally forked), unless there are some important changes not available in the original lib?

[1]: https://github.com/metachris/pdfminer
[2]: https://github.com/pdfminer/pdfminer.six

**Comment by metachris** [comment]
switched to pdfminer.six now
